//
//  Terminal.swift
//  Grammar
//
//  Created by Ulf Akerstedt-Inoue on 2023/11/20.
//  Copyright © 2020 hakkabon software. All rights reserved.
//

import Foundation

/// A terminal symbol which can occur in a string recognized by a parser and which cannot be
/// replaced by any production
public enum Terminal {

    /// Plain string.
    case string(string: String)
    
    /// Single unicode character, for example "\u{1F600}" or "😀".
//    case scalar(scalar: Unicode.Scalar)

    /// List of characters (unicde.scalars). The terminal is matched when the
//    case characterList(list: [Unicode.Scalar])

    /// Range of characters, for example "a" .. "z"
    case characterRange(range: ClosedRange<Character>)

    /// A terminal that is a regular epxression. The terminal is matched when the tokenized subsequence
    /// is contained in the language generated by the given regular expression
    case regularExpression(expression: NSRegularExpression)
    
    /// A meta-terminal that is a character that is part of the punctuation symbols that are used as
    /// markers to signify empty strings and end-of-file markers in any grammar. See `MetaSymbols`.
    case meta(MetaTerminal)
}

extension Terminal {
    
    /// Creates a terminal that is a string. The terminal is matched when the tokenized subsequence
    /// of a word is equal to this string.
    ///
    /// - Parameter string: Terminal string
    public init(string: String) {
        self = .string(string: string)
    }

//    public init(unicodeScalarLiteral value: Unicode.Scalar) {
//        self = .scalar(scalar: value)
//    }

    /// Creates a terminal that is a list of characters. The terminal is matched when the tokenized
    /// subsequence is a character contained in this list.
    ///
    /// - Parameter list: List of matched characters
//    public init(list: [Unicode.Scalar]) {
//        self = .characterList(list: list)
//    }

    /// Creates a terminal that is a range of characters. The terminal is matched when the tokenized
    /// subsequence is a character contained in this range.
    ///
    /// - Parameter range: Range of matched characters
    public init(range: ClosedRange<Character>) {
        self = .characterRange(range: range)
    }
    
    /// Creates a terminal that is a regular expression. The terminal is matched when the tokenized
    /// subsequence is contained in the language generated by the given regular expression
    ///
    /// - Parameter expression: Regular expression specifying the language matched by terminal
    /// - Throws: An error indicating that the regular expression is invalid
    public init(expression: String) throws {
        let regex = try NSRegularExpression(pattern: expression, options: [])
        self = .regularExpression(expression: regex)
    }

    /// Creates a meta-terminal.
    /// 
    /// - Parameter metaTerminal: metaTerminal description
    /// - Throws: An error indicating that the regular expression is invalid
    public init(metaTerminal: MetaTerminal) throws {
        self = .meta(metaTerminal)
    }
}

extension Terminal: ExpressibleByStringLiteral {
    public init(stringLiteral value: String) {
        self.init(string: value)
    }
}

extension Terminal: ExpressibleByUnicodeScalarLiteral {
    public init(unicodeScalarLiteral value: Unicode.Scalar) {
        self.init(string: String(value))
    }
}

extension Terminal {
    
    /// Indicates that this terminal matches the empty string and only the empty string.
    public var isEmpty: Bool {
        switch self {
        case .string(let string):
            return string.isEmpty
            
//        case .scalar(let scalar):
//            return String(UnicodeScalar(scalar)).isEmpty

//        case .characterList(list: let list):
//            return false
            
        case .characterRange:
            return false
            
        case .regularExpression(let expression):
            return expression.pattern.isEmpty
            
        case .meta(let meta):
            if meta == .eps || meta == .empty { return true }
            else { return false }
        }
    }
}


extension Terminal: Codable {
    
    private enum CodingKeys: String, CodingKey {
        case type
        case value
    }
    
    private enum TerminalCoding: String, Codable {
        case string
//        case scalar
//        case characterList
        case characterRange
        case regularExpression
        case meta
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        switch try container.decode(TerminalCoding.self, forKey: .type) {
        case .string:
            let string = try container.decode(String.self, forKey: .value)
            self = .string(string: string)
            
//        case .scalar:
//            let scalar = try container.decode(Unicode.Scalar.self, forKey: .value)
//            self = .scalar(scalar: scalar)

//        case .characterList:
//            let list = try container.decode([Unicode.Scalar].self, forKey: .value)
//            self = .characterList(list: list)

        case .characterRange:
            let range = try container.decode(ClosedRange<Character>.self, forKey: .value)
            self = .characterRange(range: range)
            
        case .regularExpression:
            let pattern = try container.decode(String.self, forKey: .value)
            self = try .regularExpression(expression: NSRegularExpression(pattern: pattern, options: []))

        case .meta:
            let rawString = try container.decode(String.self, forKey: .value)
            
            // Trim literal quote characters from the start and end of the string
            let cleanString = rawString.trimmingCharacters(in: CharacterSet(charactersIn: "\""))
            
            // Match the clean string, or fall back to .empty if it fails
            let terminal = MetaTerminal(rawValue: cleanString) ?? .empty
            self = .meta(terminal)

        }
    }
    
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        
        switch self {
        case .string(let string):
            try container.encode(TerminalCoding.string, forKey: .type)
            try container.encode(string, forKey: .value)

//        case .scalar(let scalar):
//            try container.encode(TerminalCoding.scalar, forKey: .type)
//            try container.encode(scalar, forKey: .value)

//        case .characterList(let list):
//            try container.encode(TerminalCoding.characterList, forKey: .type)
//            try container.encode(list, forKey: CodingKeys.value)

        case .characterRange(let range):
            try container.encode(TerminalCoding.characterRange, forKey: .type)
            try container.encode(range, forKey: CodingKeys.value)
            
        case .regularExpression(let expression):
            try container.encode(TerminalCoding.regularExpression, forKey: .type)
            try container.encode(expression.pattern, forKey: .value)

        case .meta(let meta):
            try container.encode(TerminalCoding.meta, forKey: .type)
            try container.encode(meta.rawValue, forKey: .value)
        }
    }
}

extension Terminal: Hashable {

    public func hash(into hasher: inout Hasher) {
        switch self {
        case .string(let string):
            hasher.combine(string.hashValue)

//        case .scalar(let scalar):
//            hasher.combine(scalar.hashValue)

//        case .characterList(let list):
//            hasher.combine(list.hashValue)

        case .characterRange(let range):
            hasher.combine(range.hashValue)

        case .regularExpression(let expression):
            hasher.combine(expression.hashValue)

        case .meta(let meta):
            hasher.combine(meta.hashValue)
        }
    }
}

/// This is the most interesting part of the `Terminal` implementation, because here is where the
/// magic happens, or more specific, the terminal is matched against the tokenized stream of input
/// that is created from the input supplied by the user.
///
/// The tokenizer or Finite State Machine examines a string segment from the input stream, builds
/// according to its understanding of lexical elements, a character class containing a certain
/// amount of the input string segment. That lexical element (character class) selects the most
/// approriate definition found in the `Terminal`, and performs a matching of the literal found
/// in the input with the definition found in `Terminal`.
///
/// Token type (class)       Terminal enum type
/// .symbol
/// .literal
/// .number
/// .keyword
/// .regex

extension Terminal: Equatable {

    /// Creates a terminal that is a string. The terminal is matched when the tokenized subsequence
    /// of a word is equal to this string.

    public static func == (lhs: Terminal, rhs: Terminal) -> Bool {
        switch (lhs, rhs) {
        case (.string(string: let ls), .string(string: let rs)):
            return ls == rs
            
        case (.characterRange(range: let lr), .characterRange(range: let rr)):
            return lr == rr
            
        case (.regularExpression(expression: let regex), .string(string: let string)):
            return string.matches(regex.pattern)

        case (.string(string: let string), .regularExpression(expression: let regex)):
            return string.matches(regex.pattern)

        case (.regularExpression(expression: let le), .regularExpression(expression: let re)):
            return le.pattern == re.pattern

        case (.meta(let lmeta), .meta(let rmeta)):
            return lmeta == rmeta

        default:
            return false
        }
    }
}

extension Terminal: CustomStringConvertible {
    
    public var description: String {
        switch self {
            
        case .string(let string) where string.contains("\""):
            let escapedValue = string.singleQuoteLiteralEscaped
            return "'\(escapedValue)'"
            
        case .string(let string):
            let escapedValue = string.doubleQuoteLiteralEscaped
            return "\"\(escapedValue)\""

//        case .scalar(let scalar):
//            return "\"\(scalar)\""

//        case .characterList(let list):
//            return list.map { "\($0)" }.joined(separator: " | ")

        case .regularExpression(let expression) where expression.pattern.contains("\""):
            let escapedValue = expression.pattern.singleQuoteLiteralEscaped
            return "'\(escapedValue)'"
            
        case .regularExpression(let expression):
            let escapedValue = expression.pattern.doubleQuoteLiteralEscaped
            return "\"\(escapedValue)\""

        case .characterRange(let range):
            let lowerString = range.lowerBound == "'" ? "\"'\"" : "'\(range.lowerBound)'"
            let upperString = range.upperBound == "'" ? "\"'\"" : "'\(range.upperBound)'"
            return "\(lowerString) ... \(upperString)"

        case .meta(let meta):
            return meta.description
        }
    }
}


extension Unicode.Scalar: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let value = try container.decode(UInt32.self)
        guard let scalar = Unicode.Scalar(value) else {
            throw DecodingError.dataCorruptedError(in: container, debugDescription: "Invalid Unicode.Scalar value")
        }
        self = scalar
    }
    
    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(self.value)
    }
}
