//
//  Terminal.swift
//  Grammar
//
//  Created by Ulf Akerstedt-Inoue on 2023/11/20.
//  Copyright © 2020 hakkabon software. All rights reserved.
//

import Foundation

/// A terminal symbol which can occur in a string recognized by a parser and which cannot be
/// replaced by any production
public enum Terminal {

    /// Plain string.
    case string(string: String)

    /// List of literal string alternatives, for example the lexical definition
    /// `EMOTICONS ::= "\u{1F600}" | "\u{1F602}"`. The terminal is matched when the
    /// tokenized subsequence is equal to any one of the strings in `list`. Widened
    /// from a plain `[Unicode.Scalar]` to `[String]` because `lexical { }` list
    /// elements are arbitrary literal tokens (e.g. multi-character keywords), not
    /// necessarily single scalars.
    case stringList(list: [String])

    /// Range of characters, for example "a" .. "z"
    case characterRange(range: ClosedRange<Character>)

    /// A terminal that is a regular epxression. The terminal is matched when the tokenized subsequence
    /// is contained in the language generated by the given regular expression
    case regularExpression(expression: NSRegularExpression)
    
    /// A meta-terminal that is a character that is part of the punctuation symbols that are used as
    /// markers to signify empty strings and end-of-file markers in any grammar. See `MetaSymbols`.
    case meta(MetaTerminal)
}

extension Terminal {
    
    /// Creates a terminal that is a string. The terminal is matched when the tokenized subsequence
    /// of a word is equal to this string.
    ///
    /// - Parameter string: Terminal string
    public init(string: String) {
        self = .string(string: string)
    }

    /// Creates a terminal that is a list of literal string alternatives. The terminal is matched
    /// when the tokenized subsequence is equal to one of the strings in this list.
    ///
    /// - Parameter list: List of matched literal alternatives
    public init(list: [String]) {
        self = .stringList(list: list)
    }

    /// Creates a terminal that is a range of characters. The terminal is matched when the tokenized
    /// subsequence is a character contained in this range.
    ///
    /// - Parameter range: Range of matched characters
    public init(range: ClosedRange<Character>) {
        self = .characterRange(range: range)
    }
    
    /// Creates a terminal that is a regular expression. The terminal is matched when the tokenized
    /// subsequence is contained in the language generated by the given regular expression
    ///
    /// - Parameter expression: Regular expression specifying the language matched by terminal
    /// - Throws: An error indicating that the regular expression is invalid
    public init(expression: String) throws {
        let regex = try NSRegularExpression(pattern: expression, options: [])
        self = .regularExpression(expression: regex)
    }

    /// Creates a meta-terminal.
    /// 
    /// - Parameter metaTerminal: metaTerminal description
    /// - Throws: An error indicating that the regular expression is invalid
    public init(metaTerminal: MetaTerminal) throws {
        self = .meta(metaTerminal)
    }
}

extension Terminal: ExpressibleByStringLiteral {
    public init(stringLiteral value: String) {
        self.init(string: value)
    }
}

extension Terminal: ExpressibleByUnicodeScalarLiteral {
    public init(unicodeScalarLiteral value: Unicode.Scalar) {
        self.init(string: String(value))
    }
}

extension Terminal {
    
    /// Indicates that this terminal matches the empty string and only the empty string.
    ///
    /// This is `true` for `.string("")` and for the meta terminals that denote the
    /// empty string — `.meta(.eps)`, `.meta(.lambda)`, and `.meta(.empty)` — regardless
    /// of which one a particular grammar has configured as its display character
    /// (see `Grammar.epsilon`). It is `false` for every other terminal, including
    /// `.meta(.eof)` and `.meta(.eop)`, which are boundary markers rather than the
    /// empty string itself.
    public var isEmpty: Bool {
        switch self {
        case .string(let string):
            return string.isEmpty
            
        case .stringList(let list):
            return list.allSatisfy { $0.isEmpty }

        case .characterRange:
            return false
            
        case .regularExpression(let expression):
            return expression.pattern.isEmpty
            
        case .meta(let meta):
            if meta == .eps || meta == .lambda || meta == .empty { return true }
            else { return false }
        }
    }
}


extension Terminal: Codable {
    
    private enum CodingKeys: String, CodingKey {
        case type
        case value
    }
    
    private enum TerminalCoding: String, Codable {
        case string
        case stringList
        case characterRange
        case regularExpression
        case meta
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        switch try container.decode(TerminalCoding.self, forKey: .type) {
        case .string:
            let string = try container.decode(String.self, forKey: .value)
            self = .string(string: string)
            
        case .stringList:
            let list = try container.decode([String].self, forKey: .value)
            self = .stringList(list: list)

        case .characterRange:
            let range = try container.decode(ClosedRange<Character>.self, forKey: .value)
            self = .characterRange(range: range)
            
        case .regularExpression:
            let pattern = try container.decode(String.self, forKey: .value)
            self = try .regularExpression(expression: NSRegularExpression(pattern: pattern, options: []))

        case .meta:
            let rawString = try container.decode(String.self, forKey: .value)
            
            // Trim literal quote characters from the start and end of the string
            let cleanString = rawString.trimmingCharacters(in: CharacterSet(charactersIn: "\""))
            
            // Match the clean string, or fall back to .empty if it fails
            let terminal = MetaTerminal(rawValue: cleanString) ?? .empty
            self = .meta(terminal)

        }
    }
    
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        
        switch self {
        case .string(let string):
            try container.encode(TerminalCoding.string, forKey: .type)
            try container.encode(string, forKey: .value)

        case .stringList(let list):
            try container.encode(TerminalCoding.stringList, forKey: .type)
            try container.encode(list, forKey: CodingKeys.value)

        case .characterRange(let range):
            try container.encode(TerminalCoding.characterRange, forKey: .type)
            try container.encode(range, forKey: CodingKeys.value)
            
        case .regularExpression(let expression):
            try container.encode(TerminalCoding.regularExpression, forKey: .type)
            try container.encode(expression.pattern, forKey: .value)

        case .meta(let meta):
            try container.encode(TerminalCoding.meta, forKey: .type)
            try container.encode(meta.rawValue, forKey: .value)
        }
    }
}

extension Terminal: Hashable {

    public func hash(into hasher: inout Hasher) {
        switch self {
        case .string(let string):
            hasher.combine(string.hashValue)

        case .stringList(let list):
            hasher.combine(list)

        case .characterRange(let range):
            hasher.combine(range.hashValue)

        case .regularExpression(let expression):
            hasher.combine(expression.hashValue)

        case .meta(let meta):
            hasher.combine(meta.hashValue)
        }
    }
}

extension Terminal: Equatable {

    /// Strict structural equality: two terminals are equal only when they are
    /// the same case with the same payload (same literal string, same range,
    /// same regex pattern, same list contents). This is a lawful equivalence
    /// relation — reflexive, symmetric, and transitive — which `Set<Terminal>`
    /// and `[Terminal: _]` (both used elsewhere in this package, e.g.
    /// `Grammar.terminals`) depend on for correctness.
    ///
    /// This intentionally does *not* check whether one terminal's pattern
    /// matches another's payload (e.g. whether a `.regularExpression` accepts
    /// a given `.string`) — that used to live here, but mixing "are these
    /// interchangeable" with "does this pattern accept that token" made `==`
    /// non-transitive (see `matches(_:)` below for the do-this-instead API,
    /// and its doc comment for a concrete counterexample of the old bug).
    public static func == (lhs: Terminal, rhs: Terminal) -> Bool {
        switch (lhs, rhs) {
        case (.string(string: let ls), .string(string: let rs)):
            return ls == rs

        case (.characterRange(range: let lr), .characterRange(range: let rr)):
            return lr == rr

        case (.regularExpression(expression: let le), .regularExpression(expression: let re)):
            return le.pattern == re.pattern

        case (.stringList(list: let ll), .stringList(list: let rl)):
            return ll == rl

        case (.meta(let lmeta), .meta(let rmeta)):
            return lmeta == rmeta

        default:
            return false
        }
    }
}

extension Terminal {

    /// Returns whether `token` satisfies this terminal's pattern. This is
    /// what a parser's `scan()` (or any other point where a grammar's
    /// expected terminal meets an already-lexed token) should call instead
    /// of `==`.
    ///
    /// Unlike `==`, this is intentionally **not** symmetric: `self` is the
    /// pattern (as it appears in a grammar's production — a `.regularExpression`,
    /// `.characterRange`, `.stringList`, or plain `.string`), and `token` is
    /// the concrete, already-scanned lexeme a lexer produced (ordinarily a
    /// `.string`). `self.matches(token)` and `token.matches(self)` can
    /// disagree, on purpose — a `.regularExpression` can accept a `.string`,
    /// but a `.string` doesn't itself define a pattern to check `self`
    /// against. This asymmetry is exactly why the logic no longer lives in
    /// `==`: `==` must be transitive for `Set<Terminal>`/`[Terminal: _]` to
    /// behave correctly, and this relation isn't. For example, with the old
    /// `==`-based version:
    /// ```
    /// let a = Terminal(range: "0" ... "9")
    /// let b = Terminal(string: "5")
    /// let c = try! Terminal(expression: "[0-9]")
    /// a == b   // true  (single digit "5" falls in 0...9)
    /// b == c   // true  ("5" matches [0-9])
    /// a == c   // false (.characterRange vs .regularExpression: no such case existed)
    /// ```
    /// `a == b` and `b == c` but `a != c` — not a lawful equivalence relation.
    /// `matches(_:)` makes no such promise, so this is no longer a problem.
    ///
    /// Two same-case terminals (e.g. comparing one grammar's regex terminal
    /// against another, rather than against a concrete token) fall back to `==`.
    public func matches(_ token: Terminal) -> Bool {
        switch (self, token) {
        case (.string(let pattern), .string(let lexeme)):
            return pattern == lexeme

        case (.characterRange(let range), .string(let lexeme)):
            return lexeme.count == 1 && range.contains(lexeme[lexeme.startIndex])

        case (.regularExpression(let regex), .string(let lexeme)):
            return lexeme.matches(regex.pattern)

        case (.stringList(let list), .string(let lexeme)):
            return list.contains(lexeme)

        case (.meta(let pattern), .meta(let lexeme)):
            return pattern == lexeme

        default:
            return self == token
        }
    }
}

extension Terminal: CustomStringConvertible {
    
    public var description: String {
        switch self {
            
        case .string(let string) where string.contains("\""):
            let escapedValue = string.singleQuoteLiteralEscaped
            return "'\(escapedValue)'"
            
        case .string(let string):
            let escapedValue = string.doubleQuoteLiteralEscaped
            return "\"\(escapedValue)\""

        case .stringList(let list):
            return list.map { "\"\($0)\"" }.joined(separator: " | ")

        case .regularExpression(let expression) where expression.pattern.contains("\""):
            let escapedValue = expression.pattern.singleQuoteLiteralEscaped
            return "'\(escapedValue)'"
            
        case .regularExpression(let expression):
            let escapedValue = expression.pattern.doubleQuoteLiteralEscaped
            return "\"\(escapedValue)\""

        case .characterRange(let range):
            let lowerString = range.lowerBound == "'" ? "\"'\"" : "'\(range.lowerBound)'"
            let upperString = range.upperBound == "'" ? "\"'\"" : "'\(range.upperBound)'"
            return "\(lowerString) ... \(upperString)"

        case .meta(let meta):
            return meta.description
        }
    }
}


extension Unicode.Scalar: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let value = try container.decode(UInt32.self)
        guard let scalar = Unicode.Scalar(value) else {
            throw DecodingError.dataCorruptedError(in: container, debugDescription: "Invalid Unicode.Scalar value")
        }
        self = scalar
    }
    
    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(self.value)
    }
}
