//
//  Grammar.swift
//  Grammar
//
//  Created by Ulf Inoue on 1/7/15.
//  Copyright © 2015 hakkabon software. All rights reserved.
//

import Foundation
import Algorithms

/// A struct representing a context-free grammar (CFG) as defined by
/// ```
///     G = (V, T, P, S), where
///
///     V is the set of nonterminals,
///     T is the set of terminals,
///     P a set of production rules, in the form P: N → (N ∪ T)*
///     S is the start symbol of the grammar.
/// ```

public struct Grammar: Codable {
    
    /// Productions for generating words of the language generated by this grammar
    public var productions: [Production]
    
    /// Productions for generating words of the language generated by this grammar
    public enum GrammarForm: String, CaseIterable, Codable {
        case none, standard, chomsky, greilbach
    }

    /// Depending on the Parsing Method, the input grammar needs to be transformed to one of
    /// { standard | chomsky | greilbach } `grammarForms` for parsing of input strings.
    public var grammarForm: GrammarForm = .none {
        willSet {
            switch newValue {
            case .none: break
            case .standard:
                let (productions, generatedNonTerminals) = rewriteToStandardForm()
                self.productions = productions
                self.generatedNonTerminals = generatedNonTerminals
            case .chomsky: //TODO
                break
            case .greilbach: //TODO
                break
            }
        }
    }
    
    /// Root non-terminal
    /// All syntax trees of words in this grammar must have a root containing this non-terminal.
    public var start: NonTerminal

    /// Defines the empty string representation (meta symbol), usually 'ε', 'λ' or ' '.
    public var epsilon: MetaTerminal = MetaTerminal.eps

    /// Defines the end of the input stream (meta symbol), usually '$' or '¶'.
    public var endofile: MetaTerminal = MetaTerminal.eof

    /// Non-terminals generated by normalizing the grammar.
    public var generatedNonTerminals: Set<NonTerminal>

    /// TODO: remove this in favour of defining Terminals as Terminal("regular-expression").
    public let lexicalTokens: [String:String]
    
    /// Parse Tree of the original grammar definition.
    /// The orignal grammar may be more sofisticated than the final grammar, which
    /// is lowered to { standard | chomsky | greilbach } used for parsing of input strings.
    public var syntaxTree: BnfExpression = .syntax([])

    /// Returns the set of all nonterminals in the grammar.
    public var nonTerminals: Set<NonTerminal> {
        return Set(productions.flatMap { production -> [NonTerminal] in
            [production.goal] + production.generatedNonTerminals
        })
    }
    
    /// Returns the set of all terminals in the grammar.
    public var terminals: Set<Terminal> {
        return Set(productions.flatMap { production -> [Terminal] in
            production.generatedTerminals
        })
    }

    /// Returns the production having the start non-terminal on the lhs in its production.
    public var startProduction: Production? {
        return productions.first(where: { $0.goal == start } )
    }
    
    /// All non-terminals which have productions which can produce an empty string
    public let nullableNonTerminals: Set<NonTerminal>
    
    /// Creates a new grammar with a given set of productions and a start non-terminal.
    ///
    /// - Parameters:
    ///   - productions: Productions for generating words
    ///   - start: Root non-terminal
    public init(productions: [Production], start: NonTerminal, lexicalTokens tokens: [String:String]) {
        self.init(productions: productions, start: start, empty: MetaTerminal.eps, lexicalTokens: tokens, generatedNonTerminals: [])
    }
}

extension Grammar {
    
    /// Creates a new grammar with a given set of productions, a start non-terminal and
    /// a set of non-terminals which have been created for normalization
    ///
    /// - Parameters:
    ///   - productions: Productions for generating words
    ///   - start: Root non-terminal
    ///   - normalizationNonTerminals: Non-terminals generated during normalization
    public init(productions: [Production], start: NonTerminal, empty: MetaTerminal, lexicalTokens tokens: [String:String], generatedNonTerminals: Set<NonTerminal>) {
        self.productions = productions
        self.start = {
            let trimChars = CharacterSet.whitespacesAndNewlines.union( CharacterSet.init(charactersIn: "<,>") )
            return NonTerminal(name: start.name.trimmingCharacters(in: trimChars))
        }()
        self.epsilon = empty
        self.lexicalTokens = tokens
        self.generatedNonTerminals = generatedNonTerminals
        
        // Compute the set of nullable non-terminals: { A in V | A =>* eps }
        // A non-terminal is nullable if it can derive the empty string.
        // Basis:
        //     All non-terminals appearing on the left-hand side of a production of the
        //     form A→ϵ are nullable.
        // Induction:
        //     If non-terminal B→α and all symbols appearing in α are variables that have
        //     been marked as nullable, then B is nullable.
        // Apply step 2 until no more variables can be marked as nullable.
        nullableNonTerminals = {
            var nullSet = Set<NonTerminal>()
            // Basis: test for the obvious empty production
            for production in productions {
                if production.isNullable { nullSet.insert(production.goal) }
            }
            if nullSet.count > 0 {
                var isNullable = true
                var size = nullSet.count
                repeat {
                    size = nullSet.count
                    for p in productions {
                        isNullable = true
                        for symbol in p.rule {
                            switch symbol {
                            case .nonTerminal(let nt):
                                if !nullSet.contains(nt) {
                                    isNullable = false
                                    break
                                }
                            case .terminal(let t):
                                if !t.isEmpty {
                                    isNullable = false
                                    break
                                }
                            case .metaSymbol(_): break
                            }
                        }
                        if isNullable {
                            nullSet.insert(p.goal)
                        }
                    }
                } while size != nullSet.count
            }
            return nullSet
        }()
    }
}

extension Grammar {
    
    public init(start: NonTerminal, @GrammarBuilder builder: () -> [Production]) {
        self.init(productions: builder(), start: start, lexicalTokens: [:])
    }
        
    public init(start: NonTerminal, @GrammarRuleBuilder builder: () -> [Rule]) {
        let _ : [Rule.Expression] = builder().map { $0.rule }
        
//        let array: String = builder().map{ "\($0)" }.joined(separator: " ")
//        let contents = """
//        "\(array)"
//        """
//        print(contents)

        let prods: String = builder().map{ "\($0.render())" }.joined(separator: "\n")
        print(prods)

        
        self.init(productions: [], start: "", lexicalTokens: [:])
    }
}

extension Grammar: Equatable {
    public static func == (lhs: Grammar, rhs: Grammar) -> Bool {
        return lhs.start == rhs.start && Set(lhs.productions) == Set(rhs.productions)
    }
}

extension Grammar: CustomStringConvertible {

    func givenOrder(productionOrder order: [String]) -> [NonTerminal:[Production]] {
        let order: [String] = Array(order.uniqued())
        let groupedProductions = Dictionary(grouping: self.productions, by: \.goal)
        let keyToPos = Dictionary(uniqueKeysWithValues: zip(order, 1...order.count))
//        let sortedGroupedProductions = groupedProductions.sorted {
        let _ = groupedProductions.sorted {
            let arg1 = String($0.key.name.prefix(while: { $0 != "-" } ))
            let arg2 = String($1.key.name.prefix(while: { $0 != "-" } ))
            return keyToPos[arg1]! < keyToPos[arg2]!
        }
//        return order.compactMap { groupedProductions[$0] }
        return [:]
    }

    /// Returns a Backus-Naur form representation of the grammar.
    public var bnf: String {
        let groupedProductions = Dictionary(grouping: self.productions, by: \.goal)
        return groupedProductions.sorted(by: {$0.key.name < $1.key.name}).map { entry -> String in
            let (pattern, productions) = entry
            let productionString = productions.map { production in
                if production.rule.isEmpty {
                    return "\"\""
                } else {
                    return production.rule.map { symbol -> String in
                        switch symbol {
                        case let .terminal(terminal):
                            return "\(terminal)"
                        case let .nonTerminal(nonterminal):
                            return "<\(nonterminal)>"
                        case let .metaSymbol(meta):
                            return "\(meta)"
                        }
                    }.joined(separator: " ")
                }
            }.joined(separator: " | ")
            return "<\(pattern.name)> ::= \(productionString)"
        }.joined(separator: "\n")
    }

    /// Returns a Extended Backus-Naur form representation of the grammar.
    public var ebnf: String {
        let groupedProductions = Dictionary(grouping: self.productions, by: \.goal)
        return groupedProductions.sorted(by: {$0.key.name < $1.key.name}).map { entry -> String in
            let (pattern, productions) = entry
            let productionString = productions.map { production in
                if production.rule.isEmpty {
                    return "\"\""
                } else {
                    return production.rule.map { symbol -> String in
                        switch symbol {
                        case let .terminal(terminal):
                            return "\(terminal)"
                        case let .nonTerminal(nonterminal):
                            return "\(nonterminal)"
                        case let .metaSymbol(meta):
                            return "\(meta)"
                        }
                    }.joined(separator: " , ")
                }
            }.joined(separator: " | ")
            return "\(pattern.name) ::= \(productionString)"
        }.joined(separator: "\n")
    }

    /// Returns a Wirth Syntax Notation form representation of the grammar.
    public var wsn: String {
        let groupedProductions = Dictionary(grouping: self.productions, by: \.goal)
        return groupedProductions.sorted(by: { $0.key.name < $1.key.name } ).map { entry -> String in
            let (pattern, productions) = entry
            let productionString = productions.map { production in
                if production.rule.isEmpty {
                    return "\"\""
                } else {
                    return production.rule.map { symbol -> String in
                        switch symbol {
                        case let .terminal(terminal):
                            return "\(terminal)"
                        case let .nonTerminal(nonterminal):
                            return "\(nonterminal)"
                        case let .metaSymbol(meta):
                            return "\(meta)"
                        }
                    }.joined(separator: " ")
                }
            }.joined(separator: " | ")
            return "\(pattern.name) = \(productionString)"
        }.joined(separator: "\n")
    }

    public var description: String {
        return bnf
    }
}
