//
//  Grammar.swift
//  Grammar
//
//  Created by Ulf Inoue on 1/7/15.
//  Copyright © 2015 hakkabon software. All rights reserved.
//

import Foundation
import Algorithms

/// A struct representing a context-free grammar (CFG) as defined by
/// ```
///     G = (V, T, P, S), where
///
///     V is the set of nonterminals,
///     T is the set of terminals,
///     P a set of production rules, in the form P: N → (N ∪ T)*
///     S is the start symbol of the grammar.
/// ```

public struct Grammar: Codable {
    
    /// Productions for generating words of the language generated by this grammar
    public var productions: [Production]
    
    /// Productions for generating words of the language generated by this grammar
    public enum GrammarForm: String, CaseIterable, Codable {
        case none, standard, chomsky, greilbach
    }

    /// Depending on the Parsing Method, the input grammar needs to be transformed to one of
    /// { standard | chomsky | greilbach } `grammarForms` for parsing of input strings.
    public var grammarForm: GrammarForm = .none {
        willSet {
            switch newValue {
            case .none: break
            case .standard:
                let (productions, generatedNonTerminals) = rewriteToStandardForm()
                self.productions = productions
                self.generatedNonTerminals = generatedNonTerminals
            case .chomsky: //TODO
                break
            case .greilbach: //TODO
                break
            }
        }
    }
    
    /// Root non-terminal
    /// All syntax trees of words in this grammar must have a root containing this non-terminal.
    public var start: NonTerminal

    /// Defines the empty string representation (meta symbol), usually 'ε', 'λ' or ' '.
    public var epsilon: MetaTerminal = MetaTerminal.eps

    /// Defines the end of the input stream (meta symbol), usually '$' or '¶'.
    public var endofile: MetaTerminal = MetaTerminal.eof

    /// Non-terminals generated by normalizing the grammar.
    public var generatedNonTerminals: Set<NonTerminal>

    /// Lexical definitions collected from a `lexical { }` block, keyed by identifier
    /// (e.g. `"Identifier"`, `"Number"`) and holding the `Terminal` each one denotes —
    /// a compiled regular expression, a character range, or a list of literal
    /// alternatives. Any occurrence of `<Identifier>` inside an ordinary production is
    /// resolved against this map by `StandardNotation`, so these lexical identifiers
    /// become real `.terminal` symbols during rewriting rather than dangling
    /// non-terminal references. See `StandardNotation.rewriteToStandardNotation`.
    public let lexicalTokens: [String: Terminal]
    
    /// Parse Tree of the original grammar definition.
    /// The orignal grammar may be more sofisticated than the final grammar, which
    /// is lowered to { standard | chomsky | greilbach } used for parsing of input strings.
    public var syntaxTree: BnfExpression = .syntax([])

    /// Returns the set of all nonterminals in the grammar.
    public var nonTerminals: Set<NonTerminal> {
        return Set(productions.flatMap { production -> [NonTerminal] in
            [production.goal] + production.generatedNonTerminals
        })
    }
    
    /// Returns the set of all terminals in the grammar.
    public var terminals: Set<Terminal> {
        return Set(productions.flatMap { production -> [Terminal] in
            production.generatedTerminals
        })
    }

    /// Returns the production having the start non-terminal on the lhs in its production.
    public var startProduction: Production? {
        return productions.first(where: { $0.goal == start } )
    }
    
    /// All non-terminals which have productions which can produce an empty string
    public let nullableNonTerminals: Set<NonTerminal>
    
    /// Creates a new grammar with a given set of productions and a start non-terminal.
    ///
    /// - Parameters:
    ///   - productions: Productions for generating words
    ///   - start: Root non-terminal
    public init(productions: [Production], start: NonTerminal, lexicalTokens tokens: [String: Terminal]) {
        self.init(productions: productions, start: start, empty: MetaTerminal.eps, lexicalTokens: tokens, generatedNonTerminals: [])
    }
}

extension Grammar {
    
    /// Creates a new grammar with a given set of productions, a start non-terminal and
    /// a set of non-terminals which have been created for normalization
    ///
    /// - Parameters:
    ///   - productions: Productions for generating words
    ///   - start: Root non-terminal
    ///   - normalizationNonTerminals: Non-terminals generated during normalization
    public init(productions: [Production], start: NonTerminal, empty: MetaTerminal, lexicalTokens tokens: [String: Terminal], generatedNonTerminals: Set<NonTerminal>) {
        self.productions = productions
        self.start = {
            let trimChars = CharacterSet.whitespacesAndNewlines.union( CharacterSet.init(charactersIn: "<,>") )
            return NonTerminal(name: start.name.trimmingCharacters(in: trimChars))
        }()
        self.epsilon = empty
        self.lexicalTokens = tokens
        self.generatedNonTerminals = generatedNonTerminals
        
        // Compute the set of nullable non-terminals: { A in V | A =>* eps }
        // A non-terminal is nullable if it can derive the empty string.
        // Basis:
        //     All non-terminals appearing on the left-hand side of a production of the
        //     form A→ϵ are nullable.
        // Induction:
        //     If non-terminal B→α and all symbols appearing in α are variables that have
        //     been marked as nullable, then B is nullable.
        // Apply step 2 until no more variables can be marked as nullable.
        nullableNonTerminals = {
            var nullSet = Set<NonTerminal>()
            // Basis: test for the obvious empty production
            for production in productions {
                if production.isNullable { nullSet.insert(production.goal) }
            }
            if nullSet.count > 0 {
                var isNullable = true
                var size = nullSet.count
                repeat {
                    size = nullSet.count
                    for p in productions {
                        isNullable = true
                        for symbol in p.rule {
                            switch symbol {
                            case .nonTerminal(let nt):
                                if !nullSet.contains(nt) {
                                    isNullable = false
                                    break
                                }
                            case .terminal(let t):
                                if !t.isEmpty {
                                    isNullable = false
                                    break
                                }
                            case .metaSymbol(_): break
                            }
                        }
                        if isNullable {
                            nullSet.insert(p.goal)
                        }
                    }
                } while size != nullSet.count
            }
            return nullSet
        }()
    }
}

extension Grammar {
    
    public init(start: NonTerminal, @GrammarBuilder builder: () -> [Production]) {
        self.init(productions: builder(), start: start, lexicalTokens: [:])
    }
        
    public init(start: NonTerminal, @GrammarRuleBuilder builder: () -> [Rule]) {
        let _ : [Rule.Expression] = builder().map { $0.rule }
        
//        let array: String = builder().map{ "\($0)" }.joined(separator: " ")
//        let contents = """
//        "\(array)"
//        """
//        print(contents)

        let prods: String = builder().map{ "\($0.render())" }.joined(separator: "\n")
        print(prods)

        
        self.init(productions: [], start: "", lexicalTokens: [:])
    }
}

extension Grammar: Equatable {
    public static func == (lhs: Grammar, rhs: Grammar) -> Bool {
        return lhs.start == rhs.start && Set(lhs.productions) == Set(rhs.productions)
    }
}

extension Grammar: CustomStringConvertible {

    /// Groups productions by their goal non-terminal and arranges the groups
    /// according to a caller-supplied ordering of non-terminal names.
    ///
    /// Any non-terminal whose base name is absent from `order` is placed
    /// after all the explicitly ordered groups, in the relative order in
    /// which it first appears in `self.productions`. This makes the function
    /// total: it never traps, and every goal in the grammar is represented
    /// exactly once in the result, whether or not `order` mentions it.
    ///
    /// - Parameter order: The desired order of (base) non-terminal names.
    ///   Duplicate entries are ignored after their first occurrence.
    /// - Returns: An array of `(goal, productions)` pairs, sorted per
    ///   `order`. A plain `Dictionary` cannot express the result of a sort,
    ///   since Swift dictionaries have no defined iteration order — using
    ///   one here would silently discard the ordering this function exists
    ///   to produce.
    func givenOrder(productionOrder order: [String]) -> [(NonTerminal, [Production])] {
        let uniqueOrder = Array(order.uniqued())
        let positionInOrder = Dictionary(uniqueKeysWithValues: zip(uniqueOrder, uniqueOrder.indices))
        
        let groupedProductions = Dictionary(grouping: self.productions, by: \.goal)
        
        // First-appearance position of each goal in `self.productions`. Used
        // both as the fallback ordering for goals missing from `order`, and
        // as a deterministic tie-breaker for generated variants that share
        // a base name (e.g. `S`, `S-1`, `S-2` all map to position of `S`).
        var seenGoals = Set<NonTerminal>()
        let appearanceOrder = self.productions.compactMap { production -> NonTerminal? in
            seenGoals.insert(production.goal).inserted ? production.goal : nil
        }
        let appearancePosition = Dictionary(uniqueKeysWithValues: zip(appearanceOrder, appearanceOrder.indices))
        
        func baseName(of goal: NonTerminal) -> String {
            String(goal.name.prefix(while: { $0 != "-" }))
        }
        
        // (bucket, primary, secondary):
        //   bucket 0 — base name found in `order`; primary = its position there.
        //   bucket 1 — not found; primary = position of first appearance.
        // `secondary` is always the appearance position, breaking ties
        // deterministically between variants that share a base name.
        func sortKey(for goal: NonTerminal) -> (Int, Int, Int) {
            let appearance = appearancePosition[goal] ?? .max
            if let pos = positionInOrder[baseName(of: goal)] {
                return (0, pos, appearance)
            }
            return (1, appearance, appearance)
        }
        
        return groupedProductions
            .sorted { lhs, rhs in
                let l = sortKey(for: lhs.key)
                let r = sortKey(for: rhs.key)
                return (l.0, l.1, l.2) < (r.0, r.1, r.2)
            }
            .map { ($0.key, $0.value) }
    }
    
    /// Returns a Backus-Naur form representation of the grammar.
    public var bnf: String {
        let groupedProductions = Dictionary(grouping: self.productions, by: \.goal)
        return groupedProductions.sorted(by: {$0.key.name < $1.key.name}).map { entry -> String in
            let (pattern, productions) = entry
            let productionString = productions.map { production in
                if production.rule.isEmpty {
                    // An empty rule denotes an epsilon production. The grammar's
                    // configured meta character (e.g. 'ε' or 'λ', see `epsilon`)
                    // is rendered here purely for display — it is never part of
                    // the stored `rule`.
                    return "\(epsilon)"
                } else {
                    return production.rule.map { symbol -> String in
                        switch symbol {
                        case let .terminal(terminal):
                            return "\(terminal)"
                        case let .nonTerminal(nonterminal):
                            return "<\(nonterminal)>"
                        case let .metaSymbol(meta):
                            return "\(meta)"
                        }
                    }.joined(separator: " ")
                }
            }.joined(separator: " | ")
            return "<\(pattern.name)> ::= \(productionString)"
        }.joined(separator: "\n")
    }

    /// Returns a Extended Backus-Naur form representation of the grammar.
    public var ebnf: String {
        let groupedProductions = Dictionary(grouping: self.productions, by: \.goal)
        return groupedProductions.sorted(by: {$0.key.name < $1.key.name}).map { entry -> String in
            let (pattern, productions) = entry
            let productionString = productions.map { production in
                if production.rule.isEmpty {
                    // See the corresponding comment in `bnf` above.
                    return "\(epsilon)"
                } else {
                    return production.rule.map { symbol -> String in
                        switch symbol {
                        case let .terminal(terminal):
                            return "\(terminal)"
                        case let .nonTerminal(nonterminal):
                            return "\(nonterminal)"
                        case let .metaSymbol(meta):
                            return "\(meta)"
                        }
                    }.joined(separator: " , ")
                }
            }.joined(separator: " | ")
            return "\(pattern.name) ::= \(productionString)"
        }.joined(separator: "\n")
    }

    /// Returns a Wirth Syntax Notation form representation of the grammar.
    public var wsn: String {
        let groupedProductions = Dictionary(grouping: self.productions, by: \.goal)
        return groupedProductions.sorted(by: { $0.key.name < $1.key.name } ).map { entry -> String in
            let (pattern, productions) = entry
            let productionString = productions.map { production in
                if production.rule.isEmpty {
                    // See the corresponding comment in `bnf` above.
                    return "\(epsilon)"
                } else {
                    return production.rule.map { symbol -> String in
                        switch symbol {
                        case let .terminal(terminal):
                            return "\(terminal)"
                        case let .nonTerminal(nonterminal):
                            return "\(nonterminal)"
                        case let .metaSymbol(meta):
                            return "\(meta)"
                        }
                    }.joined(separator: " ")
                }
            }.joined(separator: " | ")
            return "\(pattern.name) = \(productionString)"
        }.joined(separator: "\n")
    }

    public var description: String {
        return bnf
    }
}
