//
//  Production.swift
//  Grammar
//
//  Created by Ulf Akerstedt-Inoue on 2023/09/06.
//  Copyright © 2023 hakkabon software. All rights reserved.
//

import Foundation

/// A class representing a single production rule written in the form:
///      lhs -> rhs
/// where lhs is a non-terminal symbol and the rhs is alist of non-terminals and
/// terminals.
/// This class implements a production rule containing one production symbol
/// (goal symbol) and its corresponding production rule (rhs). Each symbol
/// (terminal and non-terminal) is stored in one string, so each production rule
/// concatenates all of its symbols into one array of symbols.
///
/// Note: There is a distiction between meta terminals like '[]', '{}', '()'
/// used in EBNF to defined the grammar and similar terminals '[]', '{}', '()'
/// used by the user to define his/her grammar. Fortunately, all meta terminals
/// disappear in the process of re-writing the grammar to Standard Form. This is
/// the sole reason why all symbols can be stored as plain strings.
///
/// For example, given the following production rule:
///      E -> E + T | T
/// each symbol is stored as a string and the goal represents the lhs (left to
/// the derivation symbol), and rhs represents everything to the right of the
/// derivation symbol.

public struct Production: Codable {
    
    /// Starting pattern
    public let goal: NonTerminal
    
    /// Symbols produced by substitution from the goal non terminal.
    public let rule: [Symbol]
    
    /// Creates a new production
    ///
    /// - Parameters:
    ///   - goal: Starting pattern
    ///   - production: Generated sequence of symbols
    public init(goal: NonTerminal, rule: [Symbol]) {
        self.goal = goal
        self.rule = rule
    }
    
    /// Creates a new production
    ///
    /// - Parameters:
    ///   - goal: Starting pattern
    ///   - production: Generated sequence of symbols
    ///   - chain: Non-terminals which have been filtered out during normalization
    public init(goal: NonTerminal, rule: [Symbol], chain: [NonTerminal]? = nil) {
        self.goal = goal
        self.rule = rule
    }
}

extension Production: Hashable {
    
    public func hash(into hasher: inout Hasher) {
        hasher.combine(goal)
        hasher.combine(rule)
    }
}

extension Production: Equatable {
    
    public static func == (lhs: Production, rhs: Production) -> Bool {
        return lhs.goal == rhs.goal && lhs.rule == rhs.rule
    }
}

extension Production: Comparable {

    public static func < (lhs: Production, rhs: Production) -> Bool {
        // First compare by goal symbol
        if lhs.goal != rhs.goal {
            return lhs.goal < rhs.goal
        }
        // Then compare by symbol length of rhs
        return lhs.rule.count < rhs.rule.count
    }
}

extension Production {

    init(goal: NonTerminal, @ProductionBuilder builder: () -> ProductionResult) {
        self.goal = goal

        switch builder() {
        case let .con(symbols):
            self.rule = symbols
        case let .alt(symbols):
            self.rule = symbols.flatMap { $0 }
        }
    }
}

extension Production {

    /// A production is final if it only generates terminal symbols
    public var isFinal: Bool {
        return self.rule.allSatisfy { symbol -> Bool in
            if case .terminal(_) = symbol {
                return true
            } else {
                return false
            }
        }
    }
    
    /// A production is in Chomsky normal form if it generates exactly 2 non-terminals
    /// exclusive or one or zero terminal symbols
    public var isInChomskyNormalForm: Bool {
        if isFinal {
            return rule.count == 1
        }
        return self.rule.allSatisfy { symbol -> Bool in
            if case .nonTerminal(_) = symbol {
                return true
            } else {
                return false
            }
        } && self.rule.count == 2
    }
    
    public var isNullable: Bool {
        return rule.allSatisfy { symbol in
            switch symbol {
            case .terminal(let t):
                return t.isEmpty
            case .nonTerminal(_):
                return false
            case .metaSymbol(_):
                return false
            }
        }
    }
    
    /// Sequence of terminals generated by this production
    public var generatedTerminals: [Terminal] {
        return rule.compactMap { symbol -> Terminal? in
            guard case .terminal(let terminal) = symbol  else {
                return nil
            }
            return terminal
        }
    }
    
    /// Sequence of non-terminals generated by this production
    public var generatedNonTerminals: [NonTerminal] {
        return rule.compactMap { symbol -> NonTerminal? in
            guard case .nonTerminal(let nonTerminal) = symbol else {
                return nil
            }
            return nonTerminal
        }
    }

    /// Returns true if given symbol is contained in rhs, otherwise false.
    public func containsSymbol(_ symbol: Symbol) -> (match: Bool, position: Int)? {
        for (i,s) in rule.enumerated() {
            if s == symbol {
                return (match: true, position: i)
            }
        }
        return nil
    }
}

extension Production: CustomStringConvertible {

    public var description: String {
        return "\(goal.name) --> \(rule.map { $0.description }.joined(separator: " ") )"
    }
}

extension Production: CustomDebugStringConvertible {

    public var debugDescription: String {
        return """
        production {
            goal: \(self.goal)
            rule: \(self.rule.map { $0.description } )
        }
        """
    }
}
